// packages/minuta-vue/src/components/CalendarGrid.vue
<script setup lang="ts">
import CalendarDay from "./CalendarDay.vue";
import type { CalendarGridProps } from "./types";
import CalendarWeekdays from "./CalendarWeekdays.vue";
import type { Period } from "minuta/core";
import { computed } from "vue";
import { monthGridWith } from "minuta/calendar";
import { useCalendarContext } from "./calendar-context";
import { useMinutaContext } from "#src/minuta-context";

const { locale = "en-US" } = defineProps<CalendarGridProps>();

defineSlots<{
  day?: (scope: { day: Period }) => unknown;
}>();

const DAYS_PER_WEEK = 7;

const calendar = useCalendarContext();
const minuta = useMinutaContext();
const weeks = computed(() => {
  const days = monthGridWith(
    minuta.units.value,
    minuta.browsing.value.start
  ).periods;
  const rows: Period[][] = [];
  for (let index = 0; index < days.length; index += DAYS_PER_WEEK) {
    rows.push(days.slice(index, index + DAYS_PER_WEEK));
  }
  return rows;
});

/**
 * Whether a day is the selected one.
 *
 * @param day - The day of the cell
 * @returns True for the selected day
 */
function isSelected(day: Period): boolean {
  const selected = calendar.selected.value;
  return selected !== undefined && minuta.same(selected, day, "day");
}
</script>

<template>
  <!-- The APG date picker grid: a table with role="grid" -->
  <table
    class="calendar-grid"
    role="grid"
    :aria-labelledby="calendar.labelId"
    data-testid="calendar-grid"
  >
    <CalendarWeekdays :locale="locale" />
    <tbody>
      <tr v-for="(week, row) in weeks" :key="row">
        <td
          v-for="day in week"
          :key="day.start.toISOString()"
          class="calendar-cell"
          :aria-selected="isSelected(day)"
        >
          <slot name="day" :day="day">
            <CalendarDay :day="day" :locale="locale" />
          </slot>
        </td>
      </tr>
    </tbody>
  </table>
</template>

<style scoped>
.calendar-grid {
  width: 100%;
  table-layout: fixed;
  border-collapse: separate;
  border-spacing: 0.4rem;
}

.calendar-cell {
  padding: 0;
}
</style>

// packages/minuta-react/src/components/CalendarGrid.tsx
import type { JSX, ReactNode } from "react";
import { CalendarDay } from "./CalendarDay";
import { CalendarWeek } from "./CalendarWeek";
import { CalendarWeekdays } from "./CalendarWeekdays";
import type { Period } from "minuta/core";
import { monthGridWith } from "minuta/calendar";
import { useCalendarContext } from "./calendar-context";
import { useMemo } from "react";
import { useMinutaContext } from "#src/minuta-context";

type CalendarGridProps = Readonly<{
  /** Renders one day, default: `<CalendarDay day={day} locale={locale} />` */
  children?: ((day: Period) => ReactNode) | undefined;
  /** Locale of the weekday headers and the default days, default: `"en-US"` */
  locale?: string | undefined;
}>;

const DEFAULT_LOCALE = "en-US";
const DAYS_PER_WEEK = 7;

function toWeeks(days: readonly Period[]): readonly (readonly Period[])[] {
  const weeks: Period[][] = [];
  for (let index = 0; index < days.length; index += DAYS_PER_WEEK) {
    weeks.push(days.slice(index, index + DAYS_PER_WEEK));
  }
  return weeks;
}

function weekKey(week: readonly Period[]): string {
  const [first] = week;
  if (first === undefined) {
    return "";
  }
  return first.start.toISOString();
}

/**
 * The stable month grid of the browsed month (`role="grid"`, labelled by the
 * month heading): the weekday header row, then 6 weeks of 7 days, starting
 * with the week that contains the first of the month.
 *
 * @param props - Component props
 * @param props.children - Renders one day
 * @param props.locale - Locale of the weekday headers and the default days
 * @returns The grid element
 */
function CalendarGrid({
  children,
  locale = DEFAULT_LOCALE,
}: CalendarGridProps): JSX.Element {
  const { browsing, units } = useMinutaContext();
  const { labelId } = useCalendarContext();
  const weeks = useMemo(
    () => toWeeks(monthGridWith(units, browsing.start).periods),
    [browsing, units]
  );
  const renderDay = useMemo(() => {
    if (children !== undefined) {
      return children;
    }
    function renderDefaultDay(day: Period): ReactNode {
      return <CalendarDay day={day} locale={locale} />;
    }
    return renderDefaultDay;
  }, [children, locale]);

  return (
    // oxlint-disable-next-line jsx-a11y/no-noninteractive-element-to-interactive-role -- The APG date picker grid is a table with role="grid"
    <table className="weeks-grid" role="grid" aria-labelledby={labelId}>
      <CalendarWeekdays locale={locale} />
      <tbody>
        {weeks.map((week) => (
          <CalendarWeek key={weekKey(week)} renderDay={renderDay} week={week} />
        ))}
      </tbody>
    </table>
  );
}

export { CalendarGrid };
export type { CalendarGridProps };
