// packages/minuta-vue/src/components/CalendarDay.vue
<script setup lang="ts">
import { activeDay, dayForKey } from "./day-navigation";
import { computed, nextTick, useTemplateRef } from "vue";
import type { CalendarDayProps } from "./types";
import type { Period } from "minuta/core";
import { isWeekendWith } from "minuta/calendar";
import { useCalendarContext } from "./calendar-context";
import { useMinutaContext } from "#src/minuta-context";

const { day, locale = "en-US" } = defineProps<CalendarDayProps>();

defineSlots<Record<string, never>>();

const TABBABLE = 0;
const NOT_TABBABLE = -1;
const SELECT_KEYS: ReadonlySet<string> = new Set(["Enter", " "]);

const calendar = useCalendarContext();
const minuta = useMinutaContext();
const button = useTemplateRef<HTMLButtonElement>("button");

// The labels in the units' time zone, which may differ from the runtime's
const dayNumber = computed(() =>
  new Intl.DateTimeFormat(locale, {
    day: "numeric",
    timeZone: minuta.units.value.timeZone,
  }).format(day.start)
);
const fullDate = computed(() =>
  new Intl.DateTimeFormat(locale, {
    day: "numeric",
    month: "long",
    timeZone: minuta.units.value.timeZone,
    weekday: "long",
    year: "numeric",
  }).format(day.start)
);
const isOutside = computed(
  () => !minuta.contains(minuta.browsing.value, day.start)
);
const isToday = computed(() => minuta.contains(day, minuta.now.value.start));
const isSelected = computed(() => {
  const selected = calendar.selected.value;
  return selected !== undefined && minuta.same(selected, day, "day");
});
const isDisabled = computed(() => calendar.isDisabled(day));
const isWeekend = computed(() => isWeekendWith(minuta.units.value, day));
// Only one day of the grid is tabbable: focused, selected, today or the 1st
const tabIndex = computed(() => {
  const active = activeDay(minuta, minuta.browsing.value, [
    calendar.focused.value,
    calendar.selected.value,
    minuta.period(minuta.now.value.start, "day"),
  ]);
  if (minuta.same(active, day, "day")) {
    return TABBABLE;
  }
  return NOT_TABBABLE;
});
const current = computed(() => {
  if (isToday.value) {
    return "date";
  }
  return "false";
});

/**
 * Selects the day and browses its month, unless it is disabled.
 */
function choose(): void {
  calendar.focus(day);
  if (isDisabled.value) {
    return;
  }
  calendar.select(day);
  minuta.browse(day);
}

/**
 * The grid around an element.
 *
 * @param element - The element, null before mount
 * @returns The grid, null outside of one, undefined before mount
 */
function gridOf(element: HTMLElement | null): Element | null | undefined {
  if (element === null) {
    return undefined;
  }
  return element.closest('[role="grid"]');
}

/**
 * Focuses the tabbable day of a grid.
 *
 * @param grid - The grid, if any
 */
function focusTabbable(grid: Readonly<Element> | null | undefined): void {
  if (grid === null || grid === undefined) {
    return;
  }
  const tabbable = grid.querySelector<HTMLElement>('[tabindex="0"]');
  if (tabbable !== null) {
    tabbable.focus();
  }
}

/**
 * Moves the focus to a day, browsing to its month first.
 *
 * @param target - The day to focus
 */
async function moveFocus(target: Period): Promise<void> {
  // This day may be gone after browsing, its grid stays
  const grid = gridOf(button.value);
  calendar.focus(target);
  if (!minuta.contains(minuta.browsing.value, target.start)) {
    minuta.browse(target);
  }
  await nextTick();
  focusTabbable(grid);
}

/**
 * Enter and Space select the day, the navigation keys move the focus.
 *
 * @param event - The keydown event
 */
async function navigate(event: KeyboardEvent): Promise<void> {
  const target = dayForKey(minuta, day, event);
  if (SELECT_KEYS.has(event.key)) {
    event.preventDefault();
    choose();
  } else if (target !== undefined) {
    event.preventDefault();
    if (!minuta.same(target, day, "day")) {
      await moveFocus(target);
    }
  }
}
</script>

<template>
  <button
    ref="button"
    type="button"
    class="calendar-day"
    :class="{
      'is-disabled': isDisabled,
      'is-outside': isOutside,
      'is-selected': isSelected,
      'is-today': isToday,
      'is-weekend': isWeekend,
    }"
    :tabindex="tabIndex"
    :aria-label="fullDate"
    :aria-current="current"
    :aria-disabled="isDisabled"
    @click="choose"
    @keydown="navigate"
  >
    {{ dayNumber }}
  </button>
</template>

<style scoped>
.calendar-day {
  width: 100%;
  border: none;
  border-radius: 0;
  background: #f8fafc;
  min-height: 84px;
  display: flex;
  align-items: flex-start;
  padding: 0.5rem 0.75rem;
  font-size: 1.35rem;
  font-weight: 600;
  text-align: left;
  cursor: pointer;
  transition:
    transform 0.15s ease,
    background 0.15s ease;
  color: #0f172a;
}

.calendar-day:hover {
  transform: translateY(-2px);
  background: #eef2ff;
}

.calendar-day.is-weekend {
  background: #fef2f2;
  color: #991b1b;
}

.calendar-day.is-outside {
  color: #94a3b8;
  background: #f1f5f9;
}

.calendar-day.is-today {
  outline: 2px solid #6366f1;
  outline-offset: -2px;
}

.calendar-day.is-selected {
  background: #6366f1;
  color: white;
}

.calendar-day.is-disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.calendar-day:focus-visible {
  outline: 3px solid #0f172a;
  outline-offset: 2px;
}

@media (max-width: 720px) {
  .calendar-day {
    min-height: 72px;
    padding: 0.4rem;
  }
}
</style>

// packages/minuta-react/src/components/CalendarDay.tsx
import type {
  JSX,
  KeyboardEvent,
  KeyboardEventHandler,
  RefObject,
} from "react";
import { useCallback, useEffect, useMemo, useRef } from "react";
import type { Period } from "minuta/core";
import { dayForKey } from "./day-navigation";
import { useCalendarContext } from "./calendar-context";
import { useMinutaContext } from "#src/minuta-context";

type CalendarDayProps = Readonly<{
  /** The day period of this cell */
  day: Period;
  /** Locale of the day number, weekday title and label, default: `"en-US"` */
  locale?: string | undefined;
}>;

type DayLabels = Readonly<{ full: string; number: string; weekday: string }>;

type DayState = Readonly<{
  isActive: boolean;
  isDisabled: boolean;
  isOutside: boolean;
  isSelected: boolean;
  isToday: boolean;
}>;

const DEFAULT_LOCALE = "en-US";
const TABBABLE = 0;
const NOT_TABBABLE = -1;
const SELECT_KEYS: ReadonlySet<string> = new Set(["Enter", " "]);

/**
 * The day number, the short weekday and the full date of `date` in
 * `timeZone`.
 *
 * @param date - The day's start
 * @param locale - BCP 47 locale
 * @param timeZone - The units' time zone, undefined for the runtime's
 * @returns The labels
 */
function dayLabels(
  date: Readonly<Date>,
  locale: string,
  timeZone: string | undefined
): DayLabels {
  return {
    full: new Intl.DateTimeFormat(locale, {
      day: "numeric",
      month: "long",
      timeZone,
      weekday: "long",
      year: "numeric",
    }).format(date),
    number: new Intl.DateTimeFormat(locale, {
      day: "numeric",
      timeZone,
    }).format(date),
    weekday: new Intl.DateTimeFormat(locale, {
      timeZone,
      weekday: "short",
    }).format(date),
  };
}

function dayClassName(state: DayState): string {
  const classes = ["day-cell"];
  if (state.isOutside) {
    classes.push("is-outside");
  }
  if (state.isToday) {
    classes.push("is-today");
  }
  if (state.isSelected) {
    classes.push("is-selected");
  }
  if (state.isDisabled) {
    classes.push("is-disabled");
  }
  return classes.join(" ");
}

function ariaCurrent(isToday: boolean): "date" | undefined {
  if (isToday) {
    return "date";
  }
  return undefined;
}

function tabIndex(isActive: boolean): number {
  if (isActive) {
    return TABBABLE;
  }
  return NOT_TABBABLE;
}

/**
 * Where `day` stands in the calendar: outside the browsed month, today,
 * selected, disabled or the tabbable day.
 *
 * @param day - The day period
 * @returns Its state
 */
function useDayState(day: Period): DayState {
  const { browsing, contains, now, same } = useMinutaContext();
  const { active, isDisabled, selected } = useCalendarContext();
  return {
    isActive: same(active, day, "day"),
    isDisabled: isDisabled(day),
    isOutside: !contains(browsing, day.start),
    isSelected: selected !== undefined && same(selected, day, "day"),
    isToday: contains(day, now.start),
  };
}

/**
 * Focuses the day when the keyboard moved the focus to it.
 *
 * @param day - The day period
 * @param isActive - Whether the day is the tabbable one
 * @returns The ref of the day's button
 */
function useKeyboardFocus(
  day: Period,
  isActive: boolean
): RefObject<HTMLButtonElement> {
  const { takeFocus } = useCalendarContext();
  const button = useRef<HTMLButtonElement>(null);
  useEffect(() => {
    if (isActive && takeFocus(day) && button.current !== null) {
      button.current.focus();
    }
  }, [day, isActive, takeFocus]);
  return button;
}

/**
 * The keydown handler of a day: Enter and Space select it, the navigation
 * keys move the focus.
 *
 * @param day - The day period
 * @returns The handler
 */
function useDayKeys(day: Period): KeyboardEventHandler<HTMLButtonElement> {
  const minuta = useMinutaContext();
  const { focus, select } = useCalendarContext();
  return useCallback(
    // oxlint-disable-next-line typescript/prefer-readonly-parameter-types -- React's synthetic events are mutable by design
    (event: KeyboardEvent<HTMLButtonElement>) => {
      const target = dayForKey(minuta, day, event);
      if (SELECT_KEYS.has(event.key)) {
        event.preventDefault();
        select(day);
      } else if (target !== undefined) {
        event.preventDefault();
        if (!minuta.same(target, day, "day")) {
          focus(target);
        }
      }
    },
    [day, focus, minuta, select]
  );
}

/**
 * One day cell: dimmed outside the browsed month, marked when it is today or
 * selected. A click, Enter or Space selects it; the arrow keys, Home, End,
 * PageUp and PageDown move the focus. Only the active day is tabbable.
 *
 * @param props - Component props
 * @param props.day - The day period of this cell
 * @param props.locale - Locale of the labels
 * @returns The day button
 */
function CalendarDay({
  day,
  locale = DEFAULT_LOCALE,
}: CalendarDayProps): JSX.Element {
  const { units } = useMinutaContext();
  const { select } = useCalendarContext();
  const state = useDayState(day);
  const button = useKeyboardFocus(day, state.isActive);
  const handleKeyDown = useDayKeys(day);
  const labels = useMemo(
    () => dayLabels(day.start, locale, units.timeZone),
    [day, locale, units]
  );

  const handleClick = useCallback(() => {
    select(day);
  }, [day, select]);

  return (
    <button
      ref={button}
      type="button"
      className={dayClassName(state)}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      tabIndex={tabIndex(state.isActive)}
      title={labels.weekday}
      aria-label={labels.full}
      aria-current={ariaCurrent(state.isToday)}
      aria-disabled={state.isDisabled}
    >
      <span className="date-number">{labels.number}</span>
      <span className="weekday-label">{labels.weekday}</span>
    </button>
  );
}

export { CalendarDay };
export type { CalendarDayProps };
