// packages/minuta-vue/src/components/CalendarWeekdays.vue
<script setup lang="ts">
import type { CalendarWeekdaysProps } from "./types";
import { computed } from "vue";
import { useCalendarContext } from "./calendar-context";
import { useMinutaContext } from "#src/minuta-context";

const { locale = "en-US" } = defineProps<CalendarWeekdaysProps>();

defineSlots<Record<string, never>>();

useCalendarContext();
const minuta = useMinutaContext();
const formatters = computed(() => {
  const { timeZone } = minuta.units.value;
  return {
    full: new Intl.DateTimeFormat(locale, { timeZone, weekday: "long" }),
    short: new Intl.DateTimeFormat(locale, { timeZone, weekday: "short" }),
  };
});
// The column headers of the grid: short labels abbreviating the full weekday
const weekdays = computed(() =>
  minuta
    .divide(minuta.period(minuta.browsing.value.start, "week"), "day")
    .map((day) => ({
      full: formatters.value.full.format(day.start),
      short: formatters.value.short.format(day.start),
    }))
);
</script>

<template>
  <thead class="calendar-weekdays" data-testid="calendar-weekdays">
    <tr>
      <th
        v-for="weekday in weekdays"
        :key="weekday.full"
        scope="col"
        :abbr="weekday.full"
      >
        {{ weekday.short }}
      </th>
    </tr>
  </thead>
</template>

<style scoped>
.calendar-weekdays th {
  font-size: 0.85rem;
  font-weight: inherit;
  text-transform: uppercase;
  color: #94a3b8;
  letter-spacing: 0.08em;
}
</style>

// packages/minuta-react/src/components/CalendarWeekdays.tsx
import type { JSX } from "react";
import { useMemo } from "react";
import { useMinutaContext } from "#src/minuta-context";

type CalendarWeekdaysProps = Readonly<{
  /** Locale of the weekday labels, default: `"en-US"` */
  locale?: string | undefined;
}>;

type WeekdayLabel = Readonly<{ full: string; short: string }>;

const DEFAULT_LOCALE = "en-US";

/**
 * The column headers of `CalendarGrid`: short weekday labels, abbreviating
 * the full weekday, in the week order of the units.
 *
 * @param props - Component props
 * @param props.locale - Locale of the weekday labels
 * @returns The table head with the weekday row
 */
function CalendarWeekdays({
  locale = DEFAULT_LOCALE,
}: CalendarWeekdaysProps): JSX.Element {
  const { browsing, divide, period, units } = useMinutaContext();

  const labels = useMemo((): readonly WeekdayLabel[] => {
    const { timeZone } = units;
    const full = new Intl.DateTimeFormat(locale, { timeZone, weekday: "long" });
    const short = new Intl.DateTimeFormat(locale, {
      timeZone,
      weekday: "short",
    });
    const week = period(browsing.start, "week");
    return divide(week, "day").map((day) => ({
      full: full.format(day.start),
      short: short.format(day.start),
    }));
  }, [browsing, divide, locale, period, units]);

  return (
    <thead className="weekday-grid">
      <tr>
        {labels.map((label) => (
          <th key={label.full} scope="col" abbr={label.full}>
            {label.short}
          </th>
        ))}
      </tr>
    </thead>
  );
}

export { CalendarWeekdays };
export type { CalendarWeekdaysProps };
