// packages/minuta-vue/src/components/CalendarHeader.vue
<script setup lang="ts">
import type { CalendarHeaderProps } from "./types";
import { computed } from "vue";
import { formatPeriod } from "minuta/format";
import { useCalendarContext } from "./calendar-context";
import { useMinutaContext } from "#src/minuta-context";

const { locale = "en-US" } = defineProps<CalendarHeaderProps>();

defineSlots<Record<string, never>>();

const calendar = useCalendarContext();
const minuta = useMinutaContext();
const label = computed(() =>
  formatPeriod(minuta.browsing.value, locale, {
    timeZone: minuta.units.value.timeZone,
  })
);

/**
 * Browses the previous month.
 */
function showPrevious(): void {
  minuta.browse(minuta.previous(minuta.browsing.value));
}

/**
 * Browses the next month.
 */
function showNext(): void {
  minuta.browse(minuta.next(minuta.browsing.value));
}
</script>

<template>
  <div class="calendar-header">
    <button
      type="button"
      class="nav-button"
      aria-label="Previous month"
      data-testid="calendar-previous"
      @click="showPrevious"
    >
      ← Previous
    </button>
    <h2 :id="calendar.labelId" aria-live="polite" data-testid="calendar-label">
      {{ label }}
    </h2>
    <button
      type="button"
      class="nav-button"
      aria-label="Next month"
      data-testid="calendar-next"
      @click="showNext"
    >
      Next →
    </button>
  </div>
</template>

<style scoped>
.calendar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.75rem;
}

.calendar-header h2 {
  margin: 0;
  font-size: 1.75rem;
}

.nav-button {
  border: none;
  background: #0f172a;
  color: white;
  border-radius: 0;
  padding: 0.6rem 1.2rem;
  font-weight: 600;
  cursor: pointer;
  transition: opacity 0.2s ease;
}

.nav-button:hover {
  opacity: 0.85;
}
</style>

// packages/minuta-react/src/components/CalendarHeader.tsx
import type { JSX } from "react";
import { formatPeriod } from "minuta/format";
import { useCalendarContext } from "./calendar-context";
import { useCallback } from "react";
import { useMinutaContext } from "#src/minuta-context";

type CalendarHeaderProps = Readonly<{
  /** Locale of the month label, default: `"en-US"` */
  locale?: string | undefined;
}>;

const DEFAULT_LOCALE = "en-US";
const PREVIOUS_LABEL = "← Previous";
const NEXT_LABEL = "Next →";
const PREVIOUS_NAME = "Previous month";
const NEXT_NAME = "Next month";

/**
 * The browsed month's label, which names the grid and is announced when it
 * changes, between previous and next buttons.
 *
 * @param props - Component props
 * @param props.locale - Locale of the month label
 * @returns The header element
 */
function CalendarHeader({
  locale = DEFAULT_LOCALE,
}: CalendarHeaderProps): JSX.Element {
  const {
    browse,
    browsing,
    next: nextPeriod,
    previous: previousPeriod,
    units,
  } = useMinutaContext();
  const { labelId } = useCalendarContext();

  const handlePrevious = useCallback(() => {
    browse(previousPeriod(browsing));
  }, [browse, browsing, previousPeriod]);

  const handleNext = useCallback(() => {
    browse(nextPeriod(browsing));
  }, [browse, browsing, nextPeriod]);

  return (
    <header className="toolbar-row">
      <button
        type="button"
        className="nav-button"
        onClick={handlePrevious}
        aria-label={PREVIOUS_NAME}
      >
        {PREVIOUS_LABEL}
      </button>
      <h2 id={labelId} aria-live="polite">
        {formatPeriod(browsing, locale, { timeZone: units.timeZone })}
      </h2>
      <button
        type="button"
        className="nav-button"
        onClick={handleNext}
        aria-label={NEXT_NAME}
      >
        {NEXT_LABEL}
      </button>
    </header>
  );
}

export { CalendarHeader };
export type { CalendarHeaderProps };
