// packages/minuta-vue/examples/src/DateFieldInput.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, useTemplateRef } from 'vue'
import { useDateFieldContext } from './date-field-context'

const { label } = defineProps<{
  label: string
}>()

defineSlots<Record<string, never>>()

const { element } = useDateFieldContext()
const input = useTemplateRef<HTMLInputElement>('input')

onMounted(() => {
  element.value = input.value ?? undefined
})

onBeforeUnmount(() => {
  element.value = undefined
})
</script>

<template>
  <label class="date-field-label">
    {{ label }}
    <input ref="input" class="date-field-input" inputmode="numeric" />
  </label>
</template>

<style scoped>
.date-field-label {
  display: grid;
  gap: 0.25rem;
}

.date-field-input {
  font-family: monospace;
  font-size: 1.5rem;
  padding: 0.5rem;
}
</style>

// packages/minuta-react/examples/src/DateFieldInput.tsx
import type { CSSProperties, JSX } from "react";
import { useDateFieldContext } from "./date-field-context";

type DateFieldInputProps = Readonly<{
  /** Visible label of the input */
  label: string;
}>;

const LABEL_STYLE: CSSProperties = { display: "grid", gap: "0.25rem" };
const INPUT_STYLE: CSSProperties = {
  fontFamily: "monospace",
  fontSize: "1.5rem",
  padding: "0.5rem",
};

/**
 * The labelled `<input>` the field's input-dom controller attaches to.
 *
 * @param props - Component props
 * @param props.label - Visible label of the input
 * @returns The labelled input
 */
function DateFieldInput({ label }: DateFieldInputProps): JSX.Element {
  const { inputRef } = useDateFieldContext();
  return (
    <label style={LABEL_STYLE}>
      {label}
      <input ref={inputRef} inputMode="numeric" style={INPUT_STYLE} />
    </label>
  );
}

export { DateFieldInput };
